import { ClerkProvider, auth } from '@clerk/nextjs'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import axios from 'axios'
import './globals.css'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const { userId } = auth()

  if (userId) {
    try {
      // Add your code here
      const data = await axios.post('http://localhost:3000/api/admin', { userId })  
      console.log('data =>', data) // Placeholder statement
    } catch (error) {
      console.log('error => ', error)
    }
  }
  
  return (
    <ClerkProvider>
      <html lang="en">
        <body>{children}</body>
      </html>
    </ClerkProvider>
  )
}

